# Generated by Django 2.2.7 on 2019-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'PHONE'), (2, 'FACEBOOK'), (3, 'EMAIL')], verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
            ],
        ),
    ]
