# Generated by Django 2.2.7 on 2019-12-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('phone', 'PHONE'), ('facebook', 'FACEBOOK'), ('email', 'EMAIL')], max_length=100, verbose_name='Тип контакта'),
        ),
    ]
