# Generated by Django 2.2.7 on 2019-12-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('phone', 'Телефон'), ('facebook', 'Facebook'), ('email', 'Email'), ('instagram', 'Instagram')], max_length=100, verbose_name='Тип контакта'),
        ),
    ]
