version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/prod.conf.d:/etc/nginx/conf.d
      - web-root:/opt/services/front/build
      - static_volume:/opt/services/digiskills/src/back_static
      - media_volume:/opt/services/digiskills/src/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - back
      - front
    networks:
      - nginx_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/opt/services/front/build
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/opt/services/front --email rysbai.coder@gmail.com --agree-tos --no-eff-email --staging -d digiskills.com  -d www.digiskills.com

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  db_volume:
  web-root:
  static_volume:
  media_volume: