version: '3'

services:
  back:
    build: .
    volumes:
      - .:/opt/services/digiskills
      - static_volume:/opt/services/digiskills/src/back_static
      - media_volume:/opt/services/digiskills/src/media
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db

  front:
    build: https://github.com/Aidanaaidlanova/digitalskills.git
    volumes:
      - web-root:/opt/services/front/build

  nginx:
    image: nginx:1.13
    command: nginx -g "daemon off;"
    ports:
      - 82:82
    volumes:
      - ./config/nginx/local.conf.d:/etc/nginx/conf.d
      - web-root:/opt/services/front/build
      - static_volume:/opt/services/digiskills/src/back_static
      - media_volume:/opt/services/digiskills/src/media
    depends_on:
      - back
      - front
    networks:
      - nginx_network

  db:
    image: postgres:10
    env_file:
      - src/.env
    networks:
      - db_network
    volumes:
    - db_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  web-root:
  static_volume:
  media_volume: