version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/local.conf.d:/etc/nginx/conf.d
      - web-root:/opt/services/front/build
      - static_volume:/opt/services/digiskills/src/back_static
      - media_volume:/opt/services/digiskills/src/media
    depends_on:
      - back
    networks:
      - nginx_network