# Generated by Django 2.2.7 on 2019-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('description_kg', models.TextField()),
                ('description_ru', models.TextField()),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('date', models.DateField()),
                ('location_kg', models.CharField(max_length=200)),
                ('location_ru', models.CharField(max_length=200)),
            ],
        ),
    ]
