# Generated by Django 2.2.7 on 2019-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Кыргызча')),
                ('title_ru', models.CharField(max_length=200, verbose_name='На русском')),
                ('description_kg', models.TextField(verbose_name='Кыргызча')),
                ('description_ru', models.TextField(verbose_name='На русском')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('views', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ('-id',),
            },
        ),
    ]
