# Generated by Django 2.2.7 on 2019-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',), 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_kg',
            field=models.TextField(verbose_name='Кыргызча'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(verbose_name='На русском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='location_kg',
            field=models.CharField(max_length=200, verbose_name='Кыргызча'),
        ),
        migrations.AlterField(
            model_name='news',
            name='location_ru',
            field=models.CharField(max_length=200, verbose_name='На русском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_kg',
            field=models.CharField(max_length=200, verbose_name='Кыргызча'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, verbose_name='На русском'),
        ),
    ]
