# Generated by Django 2.2.7 on 2019-12-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191207_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
