# Generated by Django 2.2.7 on 2019-12-10 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191210_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 11, 45, 38, 996261), verbose_name='Дата публикации'),
        ),
    ]
