# Generated by Django 2.2.7 on 2019-12-14 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191213_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 17, 34, 9, 428946), verbose_name='Дата публикации'),
        ),
    ]
