# Generated by Django 2.2.7 on 2019-12-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20191218_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кыргызча'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='На русском'),
        ),
    ]
