# Generated by Django 2.2.7 on 2019-12-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_name', models.CharField(max_length=200, verbose_name='Имя на кыргызском')),
                ('ru_name', models.CharField(max_length=200, verbose_name='Имя на русском')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kg', models.CharField(max_length=200, verbose_name='На русском')),
                ('name_ru', models.CharField(max_length=200, verbose_name='На кыргызском')),
                ('description_kg', models.TextField(verbose_name='На русском')),
                ('description_ru', models.TextField(verbose_name='На кыргызском')),
                ('image', models.ImageField(upload_to='course/', verbose_name='Изображение')),
                ('registration_link', models.CharField(max_length=200, verbose_name='Ссылка на регистрацию')),
                ('program', models.TextField(verbose_name='Программа курса')),
                ('start', models.DateField(verbose_name='Начало')),
                ('end', models.DateField(verbose_name='Конец')),
                ('available', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category', verbose_name='Категория')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='Преподователь')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'verbose_name': 'Видео курса',
                'verbose_name_plural': 'Видео курса',
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понидельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'verbose_name': 'Пункт расписания',
                'verbose_name_plural': 'Пункты расписания',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'verbose_name': 'Материал курса',
                'verbose_name_plural': 'Материалы круса',
            },
        ),
    ]
