# Generated by Django 2.2.7 on 2019-12-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='kg_name',
            new_name='name_kg',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ru_name',
            new_name='name_ru',
        ),
    ]
