# Generated by Django 2.2.7 on 2019-12-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191208_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(default='Teacher', max_length=300, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
