# Generated by Django 2.2.7 on 2019-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы круса'},
        ),
        migrations.AlterModelOptions(
            name='programitem',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Программы курса'},
        ),
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Расписание курса'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='description',
        ),
        migrations.AddField(
            model_name='material',
            name='description_kg',
            field=models.CharField(default='wefwef', max_length=500, verbose_name='Описание(Kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='description_ru',
            field=models.CharField(default='2wrwrw', max_length=500, verbose_name='Описание(Ru)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolesson',
            name='description_kg',
            field=models.CharField(default='wfwr2qr', max_length=500, verbose_name='Описание(Kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolesson',
            name='description_ru',
            field=models.CharField(default='wfwr', max_length=500, verbose_name='Описание(Ru)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
