# Generated by Django 2.2.7 on 2019-12-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191204_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-id',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
