# Generated by Django 2.2.7 on 2019-12-10 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191210_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 11, 37, 49, 691469), verbose_name='Дата публикации'),
        ),
    ]
