# Generated by Django 2.2.7 on 2019-12-14 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191214_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 18, 40, 2, 376888), verbose_name='Дата публикации'),
        ),
    ]
