# Generated by Django 2.2.7 on 2019-12-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20191219_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_kg',
            field=models.CharField(blank=True, default='title', max_length=200, verbose_name='Кыргызча'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, default='title', max_length=200, verbose_name='На русском'),
            preserve_default=False,
        ),
    ]
