# Generated by Django 2.2.7 on 2019-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_teacher_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_kg',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_kg',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='description', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='isOnline',
            field=models.BooleanField(default=False, verbose_name='Этот курс онлайн?'),
        ),
        migrations.AddField(
            model_name='course',
            name='link_to_video',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ссылка на трансляцию'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='programitem',
            name='content',
            field=models.TextField(default='content', verbose_name='Контент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programitem',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_link',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Начало трансляции'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about_kg',
            field=models.TextField(null=True, verbose_name='О препод. на кыргызском'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='О препод. на русском'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teacher/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ScheduleItem',
        ),
        migrations.DeleteModel(
            name='VideoLesson',
        ),
    ]
