# Generated by Django 2.2.7 on 2019-12-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191212_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='name', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
