# Generated by Django 2.2.7 on 2019-12-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191213_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link_to_video',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на трансляцию'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало трансляции'),
        ),
    ]
