# Generated by Django 2.2.7 on 2019-12-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='payload_kg',
            field=models.TextField(verbose_name='Контент на кыргызском'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='payload_ru',
            field=models.TextField(verbose_name='Контент на русском'),
        ),
    ]
