# Generated by Django 2.2.7 on 2019-12-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
